name: Generate ASCII Artwork

on:
  push

jobs:
  build_jobs_1:
    runs-on: ubuntu-latest
    steps:
     - name: Install Cowsay Program
       run: sudo apt-get install cowsay -y
        
     - name: Exicute Cowsay CMD
       run: cowsay -f dragon "Run for cover, I am DRAGON.....RAWR" >> dragon.txt   

     - name: Uplode dragon text file
       uses: actions/upload-artifact@v4
       with:
         name: dragon-text-file
         path: dragon.txt 


  test_jobs_2:
    needs: build_jobs_1
    runs-on: ubuntu-latest
    steps: 
    - name: Download dragon text file
      uses: actions/download-artifact@v4
      with:
         name: dragon-text-file
         

    - name: Test File Exists 
      run: grep -i "dragon" dragon.txt 

  deploy_jobs_3:
    needs: test_jobs_2
    runs-on: ubuntu-latest
    steps: 
    - name: Download dragon text file
      uses: actions/download-artifact@v4
      with:
         name: dragon-text-file
   
    - name:  Read File
      run: cat dragon.txt 
      
    - name: Deploy
      run: echo Deploying ... .. .   

 